### PR TITLE
Pip packaging

### PR DESCRIPTION
**Pull request by c3n21**
Hello! Since two weeks ago I started using your amazing software, that's what I missed for so long for the ultimate eye candy experience on GNOME :)

However, I've encountered few things I didn't really like about the installation process:

- I personally don't like to have a **~/bin** directory sitting in my HOME; also other Python executables uses **.local/bin** to install themselves which also conforms to the [Filesystem Hierarchy standard](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#~/.local/bin/). Related to this point, I may also point out that the libraries needed by hidamari and the executable itself are installed in the directory **.hidamari**, whereas other Python packages installs them under **~/.local/lib/`<python version>`/site-packages/`<package name>`** which is much cleaner IMO.
- Since I want to package it for Arch Linux it wasn't really a nice option having to rewrite the installation script, so I thought of making a pip package so that the installation would be as easy as building the pip-package using `python3 -m build` and `pip install .`
- pip also handles all the needed dependencies automatically without the user worrying about it.

To achieve this I had to perform a little refactor (didn't change much code really):
- each file is a package
- all the imports are absolute (like `from hidamari.<package a> import <x>, <y>`, **hidamari** is the root package)
- created **setup.cfg** and **pyproject.toml** for pip
- removed **src/hidamari** entrypoint script. If you want to run directly from terminal you can just do `python -m hidamari.__main__`.
- [TODO] update install.sh script to make use of pip for install and remove (install should be performed as user)

~Bugs:~
~- [x] Fix broken "Show hidamari"~
~- [ ] Fix `gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)` (may be related with #35)~ related to master branch

Let me know what do you think :)

### CODE REVIEW

**Comment by jeffshee** [comment]
Hi @c3n21 
Nice! I think it is a 1 step forward in the right direction ;-)
>each file is a package so that I hadn't to manually change the import inside each file

I'm not familiar with pip packaging so sorry for asking, is this the standard way? Tbh I'm more prefer to have the scripts than make all of them into packages. (It seems easier for the development)

Also, it will be best if you could have a look at the `dev` branch as well. It is WIP, has some fixes/improvements that haven't merged into the `master`. The file structure tho is a little bit different from the `master` since I'm also rewriting some portion of the codebase. I wonder if the new file structure needs some changes for pip packaging.

Thanks!

**Comment by c3n21** [comment]
> Hi @c3n21 Nice! I think it is a 1 step forward in the right direction ;-)
> 
> > each file is a package so that I hadn't to manually change the import inside each file
> 
> I'm not familiar with pip packaging so sorry for asking, is this the standard way? Tbh I'm more prefer to have the scripts than make all of them into packages. (It seems easier for the development)
> 
> Also, it will be best if you could have a look at the `dev` branch as well. It is WIP, has some fixes/improvements that haven't merged into the `master`. The file structure tho is a little bit different from the `master` since I'm also rewriting some portion of the codebase. I wonder if the new file structure needs some changes for pip packaging.
> 
> Thanks!

With each file as a package I mean that you can import them as you have always done, but they aren't a separate **pip package**.
Atm each package is installed separately under **site-packages** but I'm fixing this; I'm looking for encapsulating them under hidamari package.
I'm following along the official setuptools documentation, but it still needs some improvements.

If you don't mind I will keep improving the pip-packaging on the dev branch then.

The final result is to have a single **hidamari** package with a runnable script to run the entry point (which pip generates automatically) and the dependencies managed by pip.

**Comment by jeffshee** [comment]
I see! That makes sense.
>If you don't mind I will keep improving the pip-packaging on the dev branch then.

Yes please! And thanks for contributing!

**Comment by c3n21** [comment]
@jeffshee now I've fixed everything and it's all up to date with the dev branch; now you can install hidamari with a simple `pip install .` in hidamari's root directory and remove it cleanly with `pip uninstall hidamari`.
However the desktop file and the icon can't be handled by pip, so the install script could just run `pip install .` and copy the icon and desktop file where they should be.

**Comment by jeffshee** [comment]
@c3n21 Thanks for the contribution! I will test it on my side and will get back to you as soon as possible.
>However the desktop file and the icon can't be handled by pip

I see, so the pip can't copy files into the user directory. What if I integrate the action of copying files into the python script so that the user only need to type something like this:
`pip install hidamari && hidamari init`
Do you think this would be a better solution instead of using the install script?

**Comment by c3n21** [comment]
> @c3n21 Thanks for the contribution! I will test it on my side and will get back to you as soon as possible.
> 
> > However the desktop file and the icon can't be handled by pip
> 
> I see, so the pip can't copy files into the user directory. What if I integrate the action of copying files into the python script so that the user only need to type something like this: `pip install hidamari && hidamari init` Do you think this would be a better solution instead of using the install script?

With this approach the `res` directory should be included in `hidamari` package which is something I'm already doing for  `gui_v2.glade` in the `ui` package.

If you want to include `res` in `hidamari` then I would suggest to make this transparent: when you run `hidamari` it will check if the desktop file and the icon file are present, if not it will copy them over.

**Comment by jeffshee** [comment]
Hi @c3n21, I tested the pip package from your fork. 
Almost everything works nice, except the streaming functionality:
`ModuleNotFoundError: No module named 'ytl_wrapper'`

It seems like an import error in `video_player.py`. Could you take a look?
I will merge this soon once the issue is resolved~ 😃

**Comment by c3n21** [comment]
> Hi @c3n21, I tested the pip package from your fork. Almost everything works nice, except the streaming functionality: `ModuleNotFoundError: No module named 'ytl_wrapper'`
> 
> It seems like an import error in `video_player.py`. Could you take a look? I will merge this soon once the issue is resolved~ smiley

Just fixed, my shell script didn't replace all the imports with the absolute imports

**Comment by jeffshee** [comment]
Confirmed the fix, thanks!
Merging now =)

**Pull request merged**
